---

image: registry.gitlab.com/oosm/osm_nginx/molecule:v.1

stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip"

cache:
  paths:
    - .pip/
    - virtenv/

molecule:
  stage: test
  services:
    - docker:dind
  script:
    - pip install docker
    - pip install ansible molecule
    - ansible --version
    - molecule --version
    - molecule --debug test
