- name: Render EC2 plugin groovy from template
  template:
    src: ec2-plugin.groovy.j2
    dest: /var/lib/jenkins/init.groovy.d/99-ec2-cloud.groovy
    owner: jenkins
    group: jenkins
    mode: '0644'
  notify: Restart Jenkins
