---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
        yamllint .
platforms:
  - name: centos
    image: centos:6
  - name: ubuntu
    image: ubuntu
provisioner:
  name: ansible
  connection_options:
    ask-vault-pass: OcCeybCiWist3
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
