---
- name: Prepare
  hosts: all
  tasks:
    - name: Install Java on RedHat
      yum:
        name: java-1.8.0-openjdk
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Java on Debian
      apt:
        name: default-jdk
        state: present
      when: ansible_os_family == "Debian"
