---
- name: Prepare
  hosts: all
  tasks:
    - name: for RedHat
      block:
        - name: Install Java
          yum:
            name: java-1.8.0-openjdk
            state: present
        - name: Set JAVA_HOME if configured.
          lineinfile:
            path: /etc/environment
            line: 'JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk'
            mode: 0644
      when: ansible_os_family == "RedHat"

    - name: For Debian
      block:
        - name: Set Java version
          set_fact:
            java_home: openjdk-8-jdk
        - name: Install Java
          apt:
            name: openjdk-8-jdk
            state: present
        - name: Set JAVA_HOME if configured.
          lineinfile:
            path: /etc/environment
            line: 'JAVA_HOME=/usr/lib/jvm/openjdk-8-jdk'
            mode: 0644
      when: ansible_os_family == "Debian"
